services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: '6LcaETIqAAAAANA0jml6_iaQrQPDx3gnVCQLxOBK'
        NEXT_PUBLIC_URL_BASE: https://allez.me
    image: hugomode/shortener-url-frontend:latest             
    container_name: shortener-url-frontend
    ports:
      - "3009:3000"
    environment:      
      NODE_ENV: production
      TZ: America/Santiago
      URL_BACKEND: http://shortener-url-backend:8080/api/v1      
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}      
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
